### ISSUE TITLE
404 on testing wearables

### ISSUE THREAD

**Issue by pabloes** [decentraland/avatar-asset-test-tool#2]
Deployment on vercel of commit https://github.com/pabloes/avatar-asset-test-tool/commit/e8e9e1775b4b535739b3c86409b8d75b36cc275d

By following https://docs.google.com/document/d/1KWJCtnqvwq3hTMflH0Bmj6wHAjeZTfXCQySdl7u4yaM/edit?usp=sharing.
The wearables assets are not available in explorer, neither glb nor thumbnail.
URL used: https://play.decentraland.zone/?ALL_WEARABLES&TEST_WEARABLES=avatar-asset-test-tool-hkghe0tq1.vercel.app&position=1%2C0&realm=athena-amber

```
GET https://content.decentraland.org/contents/QmZPsa6mXLBUBcAVDH9J9L1pEAAdf15xSto3ufgXHwQbAP 404
GET https://content.decentraland.org/contents/QmZPsa6mXLBUBcAVDH9J9L1pEAAdf15xSto3ufgXHwQbAP 404
GET https://content-assets-as-bundle.decentraland.org/QmY8kddGespt6c229SkcMd9TBFcnA51yxSu4nEsbXpMNpJ 404
Error while downloading Asset Bundle: Failed to decompress data for the AssetBundle 'https://content-assets-as-bundle.decentraland.org/QmY8kddGespt6c229SkcMd9TBFcnA51yxSu4nEsbXpMNpJ'.
GET https://content-assets-as-bundle.decentraland.org/QmY8kddGespt6c229SkcMd9TBFcnA51yxSu4nEsbXpMNpJ.depmap 404
GET https://content.decentraland.org/contents/QmY8kddGespt6c229SkcMd9TBFcnA51yxSu4nEsbXpMNpJ 404
```

These CID return 404 , however these files are available in vercel deployment: avatar-asset-test-tool-hkghe0tq1.vercel.app

e.g.: https://avatar-asset-test-tool-hkghe0tq1.vercel.app/QmY8kddGespt6c229SkcMd9TBFcnA51yxSu4nEsbXpMNpJ

**Comment by nchamo** [comment]
Hey @pabloes !

Could you check again, we just deployed a fix

cc @pablitar @marcosnc

**Comment by pabloes** [comment]
everything fine , thx a lot, several projects being tested.
